<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Fabot</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Bindings.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="4.5.0" />
  </ItemGroup>
</Project>
