<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Fabot</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Bindings.fs" />
    <Compile Include="World.fs" />
    <Compile Include="Executor.fs" />
    <Compile Include="ObserveMemory.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Core/Core.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="5.2.0" />
  </ItemGroup>
</Project>
