<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Fabot.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="Atlas.fs" />
    <Compile Include="Decide.fs" />
  </ItemGroup>
</Project>
